### ISSUE TITLE
Invalidate JWT

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#10]
Requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/143720562/Invalidate+JWT

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:20 AM_
hi Ata Mahmoud please give me details to test.
The autologin should work for what time?

**Comment by Mikisson** [comment]
**Ata Mahmoud** _July 13, 2020, 11:59 AM_

Hello Ray Zaragoza 
I think you need to do the following:

1. log in with a user using postman and save the token.
2. logout the user using postman and the token you got at login.
3. try to call any endpoint with this token. it shouldn't work and you should get an error message

**Comment by diegopau** [comment]
From Ray:
Test passed

**Comment by KanikaDevops** [comment]
Storypoints =10
