### ISSUE TITLE
Incorrect the message displayed for deleting a lighting scene

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-web-server#100]
Actual Result: The lighting scene is deleted, however, it displays an error message
Expected Result: Success message is displayed
Video: https://drive.google.com/file/d/1XZzqGQ3BXu82Wz0MubZuR-RADMw8qT91/view?usp=sharing

**Comment by olagalal** [comment]
@Ray-LZ I think you may clicked the button twice. So the second time the lightScene was not there.
Anyway I added a message when you delete the lightScene.

**Comment by Ray-LZ** [comment]
Hi @olagalal I was able to reproduce it. This time I make sure I didn't tap the button twice
https://drive.google.com/file/d/1mDpI8x_4EH8OWNbxi3FNvGbOvpc1iu97/view?usp=sharing

**Comment by olagalal** [comment]
@Rat test again

**Comment by olagalal** [comment]
@Ray-LZ I fixed it, check again please.

**Comment by Ray-LZ** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46169036/99688961-ff5b0100-2a4b-11eb-83e2-d5f53a2a0d45.png)
