### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#11]
Requirements link:  https://scissorboy.atlassian.net/wiki/spaces/O/pages/143687835/Auto+Login

you can find the endpoint at the postman collection

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 6, 2020, 2:02 PM_
Test pass
Get Auto login
https://oceanbuilders.herokuapp.com/v1/api/auth/me

![image-20200206-204714](https://user-images.githubusercontent.com/72101387/95999660-662a4080-0e36-11eb-8e64-834f0f58e8c7.png)

![image-20200206-204625](https://user-images.githubusercontent.com/72101387/95999698-6f1b1200-0e36-11eb-86d8-aca3cd1663b8.png)

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented

**Comment by KanikaDevops** [comment]
Storypoints =17.5
