### ISSUE TITLE
update swagger doc

### ISSUE THREAD

**Issue by olagalal** [oceanbuilders/ob-web-server#115]
Update swagger doc on ob-webserver.

Acceptance Critera
--------------------
1. Updating from Swagger 2 to Open API 3.
2. Add other endpoints that are not currently in documentation.

**Comment by scottdear** [comment]
Hi @olagalal hope all is well, want to see how this one is coming.  @godslave05 is working on an OpenAPI 3.0 spec for the light turning on/off stuff.   This would be great to have to enable some automated testing.

**Comment by scottdear** [comment]
@ola I'm moving this to the to-do column for this sprint.   Also once you've updated swagger can you create and check in an Open API 3.0 file w/ this definition.  This should be at the top of the priority list.

**Comment by angiedear** [comment]
@olagalal can I get a status update for this one please?

**Comment by scottdear** [comment]
Can we get the yaml file checked into the ob-web-server repo, created a PR, and add Asad and I as reviewers.

**Comment by angiedear** [comment]
Hi Ola, can I get a status update for this one please?

**Comment by olagalal** [comment]
> Hi Ola, can I get a status update for this one please?

work in progress

**Comment by olagalal** [comment]
https://oceanbuilders.herokuapp.com/v1/docs/

**Comment by angiedear** [comment]
Hi Ola, does the link above need review or are you just showing progress?

**Comment by olagalal** [comment]
> Hi Ola, does the link above need review or are you just showing progress?

this is the old swagger 2 doc, the progress is on oas3_doc branch, you can check it.

**Comment by olagalal** [comment]
#132

**Comment by olagalal** [comment]
#132 related PR

**Comment by scottdear** [comment]
Ah so do the changes in #132 address this issue as well?  If so, please move this do done after you have merged the PR into the master branch.
