### ISSUE TITLE
Make an open API Spec 3.0 in JSON 

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/ob-web-server#119]
Based on the current endpoints made available on the NodeJS server that is running on the pie, document the current API using the [OpenAPI specification 3.0](https://swagger.io/specification/).  When done create a PR w/ the open API spec (use JSON format) in the webserver repo.

**Comment by angiedear** [comment]
T-Shirt size = medium

**Comment by angiedear** [comment]
@godslave05 can you let me know where you're at with this issue?  It should be moving over to the in progress column so that it can be finished by Monday.

**Comment by godslave05** [comment]
I am working on it, could not give much time but hope in next couple of days I will be able to create the swagger doc

**Comment by godslave05** [comment]
This is where I am at now. Could you review to see I am on right track.

openapi: 3.0.0
info:
  version: 1.0.0.0
  title: 'light control api'
  description: 'A prototype API to control light on seapod'

servers:
  - https://oceanbuilders.herokuapp.com/v1

# Basic authentication   
components:
  securitySchemes:
      type: apikey
      in: header
      name: X-Auth-Token
    security:
      - ApiKeyAuth: []
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Light:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the light.
        status:
          type: bool
          description: On/Off status of the light.
        color:
          type: hex
          descriotion: Color of the light.   
      required:
        - id   
  parameters:
    Id:
      name: id
      in: query
      description: Limits the number of items on a page
      schema:
        type: integer
      
paths:
  # this operation returns the list of available lights
  /lights:
    get:
      description: Returns a list of lights.
      responses:
        '200':
          description: Successfully returned a list of lights.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Light'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  # this operation returns a light details              
  /lights/{id}:
    get:
      description: Obtain information about a light
      parameters:
        - $ref: '#/components/parameters/Id' 
      response:
        '200':
          description: Successfully returned a light
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Light'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

**Comment by angiedear** [comment]
@scottdear could you take a look at Asad's code please?

**Comment by scottdear** [comment]
Oops sorry didn't mean to close this.  Please have a look at the gist, I left some comments, once you've implemented those, please create a pull request in the flutter repo w/ that API spec.

**Comment by godslave05** [comment]
@scottdear I have updated the gist with 1st version of the api spec.

**Comment by scottdear** [comment]
Add this to ob-web-sever repository create a PR and add Ola and I as reviewers, then move this issue to In Review

**Comment by angiedear** [comment]
You can merge this pull request per Scott

**Comment by angiedear** [comment]
Hi Asad, you can go ahead and merge this pull request per Scott.

**Comment by scottdear** [comment]
merged and purged
