### ISSUE TITLE
Add endpoints for light services to NodeJS server (PodServer) on Pi

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-web-server#125]
Update the webserver to support the following endpoints to provide an authentication layer in front of the controller server (that only listens on localhost).  The controller server does not have authentication so the NodeJS server must provide authentication in front of these endpoints.  The Controller server API will be created on oceanbuilders/smartpod#4 

These endpoints will accept connection from outside the Pi and authenticate them or refuse the connection with a 401 error.

Endpoints
-------------
/lights - will return the contents of the call to the Controller API /lights call
/light/<light_id> - will provide the contents of the corresponding call to the Controller API.

**Comment by olagalal** [comment]
[related PR](https://github.com/oceanbuilders/ob-pod-server/pull/1)
