### ISSUE TITLE
Update nodejs to fix security issues

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-web-server#127]
npm install shows:
found 20 vulnerabilities (10 low, 2 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by olagalal** [comment]
<img width="669" alt="Screen Shot 2021-04-10 at 11 44 23 PM" src="https://user-images.githubusercontent.com/12789198/114285334-b0435600-9a56-11eb-9de1-8b10ffc61c2a.png">
