### ISSUE TITLE
Migrate to AWS server

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-web-server#129]
Migrate existing software to AWS instance
Document process so we can script the install later.
Deploy the code for ob-web-server
Deploy the code for raspberry-pi server (If needed).

**Comment by scottdear** [comment]
Needs to get access from outside world to be able to test this remotely.  This will need a hole in the firewall.  on Port 443 and an SSL certificate provisioned.

**Comment by olagalal** [comment]
- Deployed the code for ob-web-server, and ob-raspberrypi-server, and Working on background:
> Notes:
> 1. It is working locally but we need to add access from outside
> 2. ob-raspberrypi-server used to connect to local MariaDB server, it's not working right now or setup yet.

- Installed mongodb and mysql
- Installed yarn and pm2

Next:
- Wait until Scott add access from outside on port 403
- Finish the documentation of the process

Questions:
- Should we have local mongo database or just connect to the one hosted on cloud.mongodb.com?
- Should we install phpMyAdmin to view mysql database?

**Comment by angiedear** [comment]
Hi Ola, are you blocked on this issue currently?

**Comment by olagalal** [comment]
> Hi Ola, are you blocked on this issue currently?

yes, I am waiting for Scott to finish https://github.com/oceanbuilders/ob-iac/issues/6 and https://github.com/oceanbuilders/ob-iac/issues/5

**Comment by scottdear** [comment]
Software was moved, we will not be installing/configuring backups to new software.
