### ISSUE TITLE
Access disable

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#13]
Requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/143687861/Access+Disable

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:24 AM_
Not implemented (currently we have the remove user button)
Diego Ocampo disable user do we need an additional button same as we have one for removing users in the access management page?

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 5:25 PM_
Abdullah Asad please link it with an OBF card when this is implemented

**Comment by Mikisson** [comment]
**Diego Ocampo** _July 14, 2020, 3:17 PM_
Ray Zaragoza I did some temporary quick buttons for 0.8 https://www.figma.com/file/QvXwkDejI8eVzt6d335KvY/OB-0.8?node-id=291%3A2 this is enough for now, just to know the functionality is there.

**Comment by olagalal** [comment]
@godslave05 I need more details about what is required.

**Comment by olagalal** [comment]
https://oceanbuilders.herokuapp.com/v1/api/seapods/:seapodId/users/:userId

Access Disable is different from 'Remove seapod member'
but both only the admin can request them
