### ISSUE TITLE
Add Members (Already Registered Members)

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#14]
Requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/143687875/Add+Members

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:28 AM_
test the grant access request

**Comment by diegopau** [comment]
From Ray:
Test passed
![IMG_2136](https://user-images.githubusercontent.com/315149/96748872-6f815300-13ca-11eb-8dc8-db6007f4f535.png)

**Comment by KanikaDevops** [comment]
Storypoints =10
