### ISSUE TITLE
Remove Members

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#15]
Requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/143720625/Remove+Members

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:30 AM_
remove user access management page ready to test

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:30 AM_
remove user access management page ready to test

**Comment by Mikisson** [comment]
**Ray Zaragoza** _August 7, 2020, 3:25 PM_
I’m having this error in both Android & iOS

![image-20200807-202531](https://user-images.githubusercontent.com/72101387/96002230-2c0e6e00-0e39-11eb-9ecc-b870ce2590a4.png)

**Comment by diegopau** [comment]
From Ray:
Hi Ola Galal please check this, I’m able to reproduce it, there’s nothing wrong with my internet
![IMG_0006](https://user-images.githubusercontent.com/315149/96748794-511b5780-13ca-11eb-8112-66364b6eb72a.png)

**Comment by diegopau** [comment]
From Ola:
I will check it

**Comment by olagalal** [comment]
@Ray-LZ @diegopau  I checked for this Error, it's not a server side error. I searched and I think it's related to something called 'DioError' in flutter, @godslave05 could you please help me to figure out why this error is returning?

**Comment by godslave05** [comment]
fixed in 0.7+10

**Comment by godslave05** [comment]
fixed in 0.7+11
