### ISSUE TITLE
Build new ocean builder

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#16]
Requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/143687907/Build+new+ocean+builder

you can find the endpoint at the postman collection

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 6, 2020, 3:06 PM_
Test Pass 
Post Create New Seapod
https://oceanbuilders.herokuapp.com/v1/api/seapods

![image-20200206-210556](https://user-images.githubusercontent.com/72101387/96002872-e900ca80-0e39-11eb-8577-df7fc52b9a61.png)

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented

**Comment by KanikaDevops** [comment]
Storypoints =10
