### ISSUE TITLE
Get Sea pod information by Id

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#17]
Requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/143655194/Get+Sea+pod+information

you can find the endpoint at the postman collection

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 11:33 AM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented

**Comment by KanikaDevops** [comment]
Storypoints=10
