### ISSUE TITLE
Create Lighting scenes

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#19]
requirements link: https://scissorboy.atlassian.net/wiki/spaces/O/pages/144769035/Create+Lighting+scenes

you can find the endpoint at the postman collection

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented

**Comment by KanikaDevops** [comment]
Storypoints=10
