### ISSUE TITLE
[admin panel] Admin Login

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#26]
You can find the endpoint at the postman collection.

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 11:35 AM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by olagalal** [comment]
@shimaaelhosary done, please test it from your side
