### ISSUE TITLE
Fake Location Generator

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#28]
At Creating new seapod the app generate a random fake location to the seapod at panama on the ocean.

![Capture](https://user-images.githubusercontent.com/72101387/96028882-31c87b80-0e5a-11eb-86d4-d12868ee8c3b.PNG)

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 11:35 AM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented

**Comment by KanikaDevops** [comment]
Storypoints =10
