### ISSUE TITLE
Fake Data Generator

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#29]

**Comment by Mikisson** [comment]
**Ray Zaragoza** _March 31, 2020, 5:07 PM_
where is this fake data displayed? how can I test Ata Mahmoud

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:39 AM_
Need to be implemented in the app side, currently we display fake data from the app

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 5:29 PM_
Hi Abdullah Asad please link this with an OBF card when the app pulls the data from the server

**Comment by Ray-LZ** [comment]
This is implemented
