### ISSUE TITLE
The server crashes

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-web-server#3]
When the app faces issues it will make the server crash, this happened while:

- Testing lighting scenes

- It happened before while testing the reset password link.

`Oct 12 08:54:04 oceanbuilders heroku/web.1 State changed from starting to up
Oct 12 08:54:10 oceanbuilders app/web.1 {"error":{},"level":"error","message":"uncaughtException: Cannot read property 'status' of undefined\nTypeError: Cannot read property 'status' of undefined\n    at LightiningSceneService.updateLightStatus (/app/services/lightiningScene.js:513:45)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /app/routes/lightiningScenes.js:163:20","stack":"TypeError: Cannot read property 'status' of undefined\n    at LightiningSceneService.updateLightStatus (/app/services/lightiningScene.js:513:45)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /app/routes/lightiningScenes.js:163:20","exception":true,"date":"Mon Oct 12 2020 15:54:10 GMT+0000 (Coordinated Universal Time)","process":{"pid":23,"uid":24848,"gid":24848,"cwd":"/app","execPath":"/app/.heroku/node/bin/node","version":"v13.1.0","argv":["/app/.heroku/node/bin/node","/app/index.js"],"memoryUsage":{"rss":66924544,"heapTotal":30109696,"heapUsed":27512432,"external":19594738}},"os":{"loadavg":[5.9990234375,3.17724609375,2.4228515625],"uptime":1715340},"trace":[{"column":45,"file":"/app/services/lightiningScene.js","function":"LightiningSceneService.updateLightStatus","line":513,"method":"updateLightStatus","native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false},{"column":20,"file":"async /app/routes/lightiningScenes.js","function":null,"line":163,"method":null,"native":false}]}
Oct 12 08:54:12 oceanbuilders heroku/router at=error code=H13 desc="Connection closed without response" method=PUT path="/v1/api/lightining-scenes/5f7b10fb5b6b430017643b31/lightStatus" host=oceanbuilders.herokuapp.com request_id=31f4a21f-1d3e-4c91-ac9e-606567a3c271 fwd="187.190.153.91" dyno=web.1 connect=1ms service=46ms status=503 bytes=0 protocol=https
Oct 12 08:54:12 oceanbuilders app/web.1 {"error":{},"level":"error","message":"uncaughtException: Cannot read property 'status' of undefined\nTypeError: Cannot read property 'status' of undefined\n    at LightiningSceneService.updateLightStatus (/app/services/lightiningScene.js:513:45)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /app/routes/lightiningScenes.js:163:20","stack":"TypeError: Cannot read property 'status' of undefined\n    at LightiningSceneService.updateLightStatus (/app/services/lightiningScene.js:513:45)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /app/routes/lightiningScenes.js:163:20","exception":true,"date":"Mon Oct 12 2020 15:54:11 GMT+0000 (Coordinated Universal Time)","process":{"pid":23,"uid":24848,"gid":24848,"cwd":"/app","execPath":"/app/.heroku/node/bin/node","version":"v13.1.0","argv":["/app/.heroku/node/bin/node","/app/index.js"],"memoryUsage":{"rss":67440640,"heapTotal":30633984,"heapUsed":27631240,"external":19594794}},"os":{"loadavg":[6.88037109375,3.40673828125,2.50146484375],"uptime":1715341},"trace":[{"column":45,"file":"/app/services/lightiningScene.js","function":"LightiningSceneService.updateLightStatus","line":513,"method":"updateLightStatus","native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false},{"column":20,"file":"async /app/routes/lightiningScenes.js","function":null,"line":163,"method":null,"native":false}]}
Oct 12 08:54:12 oceanbuilders app/web.1 /app/node_modules/winston/lib/winston/logger.js:307
Oct 12 08:54:12 oceanbuilders app/web.1       throw ex;
Oct 12 08:54:12 oceanbuilders app/web.1       ^
Oct 12 08:54:12 oceanbuilders app/web.1 
Oct 12 08:54:12 oceanbuilders app/web.1 NodeError: write after end
Oct 12 08:54:12 oceanbuilders app/web.1     at writeAfterEnd (/app/node_modules/readable-stream/lib/_stream_writable.js:257:12)
Oct 12 08:54:12 oceanbuilders app/web.1     at PassThrough.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:301:21)
Oct 12 08:54:12 oceanbuilders app/web.1     at File.log (/app/node_modules/winston/lib/winston/transports/file.js:185:34)
Oct 12 08:54:12 oceanbuilders app/web.1     at ExceptionStream._write (/app/node_modules/winston/lib/winston/exception-stream.js:48:29)
Oct 12 08:54:12 oceanbuilders app/web.1     at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:405:139)
Oct 12 08:54:12 oceanbuilders app/web.1     at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:394:5)
Oct 12 08:54:12 oceanbuilders app/web.1     at ExceptionStream.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:303:11)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.ondata (/app/node_modules/readable-stream/lib/_stream_readable.js:662:20)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.emit (events.js:215:7)
Oct 12 08:54:12 oceanbuilders app/web.1     at addChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:297:12)
Oct 12 08:54:12 oceanbuilders app/web.1     at readableAddChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:279:11)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.Readable.push (/app/node_modules/readable-stream/lib/_stream_readable.js:240:10)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.Transform.push (/app/node_modules/readable-stream/lib/_stream_transform.js:139:32)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger._transform (/app/node_modules/winston/lib/winston/logger.js:305:12)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.Transform._read (/app/node_modules/readable-stream/lib/_stream_transform.js:177:10)
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)
Oct 12 08:54:12 oceanbuilders app/web.1 Emitted 'error' event on PassThrough instance at:
Oct 12 08:54:12 oceanbuilders app/web.1     at writeAfterEnd (/app/node_modules/readable-stream/lib/_stream_writable.js:259:10)
Oct 12 08:54:12 oceanbuilders app/web.1     at PassThrough.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:301:21)
Oct 12 08:54:12 oceanbuilders app/web.1     [... lines matching original stack trace ...]
Oct 12 08:54:12 oceanbuilders app/web.1     at DerivedLogger.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! code ELIFECYCLE
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! errno 7
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! ob-web-server@0.7.0 start: `node index.js`
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! Exit status 7
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! 
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! Failed at the ob-web-server@0.7.0 start script.
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Oct 12 08:54:12 oceanbuilders app/web.1 
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR! A complete log of this run can be found in:
Oct 12 08:54:12 oceanbuilders app/web.1 npm ERR!     /app/.npm/_logs/2020-10-12T15_54_11_860Z-debug.log
Oct 12 08:54:12 oceanbuilders heroku/web.1 Process exited with status 7`

**Comment by olagalal** [comment]
@Ray-LZ I fixed this, please check if it still occur.

**Comment by Ray-LZ** [comment]
Not able to reproduce
