### ISSUE TITLE
Urgent notification sender

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#30]

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:21 AM_
needs to be implemented in the app side

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 5:24 PM_
Abdullah Asad please link it with an OBF card when this is implemented

**Comment by Ray-LZ** [comment]
This is implemented
