### ISSUE TITLE
[admin panel] Users Listing

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#32]
what i did?

- I developed an endpoint to get all users at the database.
- to access all users you should be an admin so i developed a middle ware to prevent none admins from accessing users data.
- the endpoint filters the user passwords and json web token, so it didn’t return these data at the response.

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 2:00 PM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by olagalal** [comment]
waiting for a specific properties of user that I should return.
