### ISSUE TITLE
Update Seapod Name

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#33]
You can find the endpoint at postman collection.

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 11:36 AM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented

**Comment by KanikaDevops** [comment]
Storypoints=10

**Comment by KanikaDevops** [comment]
Storypoints=10
