### ISSUE TITLE
[admin panel] Admin Auto Login API

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#34]
- I created an endpoint that enable admin to auto login using the json web token.
- the endpoint validate the token and check if the user is admin or not
- if the user is admin the app will look for the admin data.
- finally the app will return the admin data or the error message with a status code

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 11:40 AM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by olagalal** [comment]
@shimaaelhosary done, please test it from your side
