### ISSUE TITLE
[admin panel] Get User Seapods api

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#35]
An endpoint to get the user seapods using the JSON web token of the user.

- the app validate the token and return the seapods of this users.
- also the app filters the seapods from any data that is n’t allowed to be seen by the user

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 12, 2020, 11:36 AM_
test pass

**Comment by KanikaDevops** [comment]
Storypointed
