### ISSUE TITLE
Update Access Request At Resend

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#36]

**Comment by Mikisson** [comment]
**Ray Zaragoza** _March 31, 2020, 5:04 PM_
Ata Mahmoud what should I test here?

**Comment by Mikisson** [comment]
**Ray Zaragoza** _June 29, 2020, 11:55 AM_
pending new build with access request fixed

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:17 AM_
ready to test

**Comment by diegopau** [comment]
From Ray:
Test passed

**Comment by KanikaDevops** [comment]
Storypoints =10
