### ISSUE TITLE
QR code is not displayed in the apps

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-web-server#4]
Actual result:
The seapod information page is not displaying the QR code image

![IMG_2096](https://user-images.githubusercontent.com/46169036/95772034-b613d680-0c81-11eb-938f-d40b4ca30413.PNG)

**Comment by olagalal** [comment]
@godslave05 this should be assigned to you?

**Comment by olagalal** [comment]
@godslave05 please check this?

**Comment by godslave05** [comment]
@olagalal I am getting internal server error when trying to download an qrcode image.
Like this one 
https://oceanbuilders.herokuapp.com/qrcodes/S9CA9C1.png

**Comment by olagalal** [comment]
@Ray-LZ @godslave05 bug is solved, but for newly created seapod. So you should reset the db before testing this.

**Comment by olagalal** [comment]
@Ray-LZ test this please

**Comment by Ray-LZ** [comment]
Test pass iOS & Android
![image](https://user-images.githubusercontent.com/46169036/103919053-34dbac80-50d5-11eb-9d74-0ccfbcf1b03a.png)
