### ISSUE TITLE
Unite and Integration Tests

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#40]

**Comment by Mikisson** [comment]
**Ola Galal** _June 1, 2020, 1:21 AM_

updates: I start writing integration tests: 

- services/accessRequest [60% done]

(it contains many branches to different files, so the coverage raised from 22 branch to 83 branch )

**_coverage report_**

![sc01](https://user-images.githubusercontent.com/72101387/96035256-101fc200-0e63-11eb-8b4d-821ae12236b7.png)

**Comment by Mikisson** [comment]
**Ola Galal** _June 2, 2020, 12:59 AM_

updates: 

- services/accessRequest [88.35% done]
- routes/accessRequest.js [100% done]

(it contains many branches to different files, so the coverage raised from 83 branch to 137 branch )

**_coverage report_**

![sc02](https://user-images.githubusercontent.com/72101387/96035415-4c532280-0e63-11eb-97d7-389059e5d797.png)

**Comment by Mikisson** [comment]
**Ola Galal** _June 17, 2020, 8:07 PM_

(it contains many branches to diffrent files, so the coverage rised from 137 branch to 228 branch )

**_coverage report_**

![sc03](https://user-images.githubusercontent.com/72101387/96035571-77d60d00-0e63-11eb-845c-999ccf38a807.png)

**Comment by Mikisson** [comment]
**Ola Galal** _June 24, 2020, 5:49 PM_

(the coverage rised from 228 branch to 264 branch )
62.52% Statements 1156/1849

**_coverage report_**

![sc04](https://user-images.githubusercontent.com/72101387/96035647-9cca8000-0e63-11eb-82ff-9b9358ba83a4.png)

**Comment by Mikisson** [comment]
**Ola Galal** _June 27, 2020, 6:11 PM_

(it contains many branches to different files, so the coverage raised from 264 branch to 395 branch )

**_coverage report_**

![sc05](https://user-images.githubusercontent.com/72101387/96035760-c683a700-0e63-11eb-9874-2d7a871ec224.png)

**Comment by diegopau** [comment]
Ola Galal
2 days ago

Ray Zaragoza Kanika Tiwari  this issue starting from 25 March to 28 June, it took a lot of time, becasue I wrote test cases for all the code. I tracked my progress by comments. I can’5 estimate the time.

**Comment by diegopau** [comment]
Ray Zaragoza
2 days ago

Thanks Ola Galal
