### ISSUE TITLE
2 popups displayed simultaneously

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#43]
Actual Result:When the user edits simultaneously "emergency contact" and "user profile details” and saves the changes, there are 2 popups displayed at the same time 1 for emergency contact the other one for user profile (with different text on them)

**Comment by Mikisson** [comment]
**Abdullah Asad** _March 31, 2020, 10:17 AM_
Ray Zaragoza, Should I show the confirmation in a single Popup ?

**Comment by Mikisson** [comment]
**Ray Zaragoza** _April 13, 2020, 11:12 AM_
yes, 1 popup is definitely better. Abdullah Asad 
Diego Ocampo can we merge the popups into 1? 
expected result:
it doesn’t matter if the user edited the emergency contact or the user’s details or if it was edited both at the same time we will always display the same popup “Your Profile page has been updated”

**Comment by Mikisson** [comment]
**Abdullah Asad** _April 13, 2020, 9:30 PM_
Yes it is done. User will get this message when edited both of them. Otherwise will get separate message for each of them

**Comment by Mikisson** [comment]
**Ray Zaragoza** _May 14, 2020, 6:41 PM_
test passed

**Comment by Ray-LZ** [comment]
This is fixed tested with app version 0.7.0(9)
I have reported a small issue related to this popup #148
