### ISSUE TITLE
Redirect after popup is displayed (light scene name duplicated)

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#44]
Expected Result: When a user tries to create a new lighting scene with a duplicated name, we should alert the user this is not a valid name and the app should redirect to this page.

![image-20200331-234020](https://user-images.githubusercontent.com/72101387/96113117-f70b2580-0ee3-11eb-8a11-15a237da3294.png)

**Comment by Mikisson** [comment]
**Ray Zaragoza** _May 14, 2020, 5:57 PM_
Test failed

**Comment by diegopau** [comment]
From Ray:
Test passed
