### ISSUE TITLE
Add update all light scenes

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#46]

**Comment by Mikisson** [comment]
**Abdullah Asad** _April 6, 2020, 6:55 AM_
Ola Galal 
Not working 
Getting this error when trying to update all scenes to change the orders in lighting scene list screen
”Duplicated Scene Name!”
Please check.

**Comment by Mikisson** [comment]
**Ola Galal** _April 6, 2020, 12:40 PM_
Abdullah Asad This function isn’t for order the light scenes, it is for updating many light scenes at a time.

**Comment by Mikisson** [comment]
**Abdullah Asad** _April 7, 2020, 5:02 AM_
Ola Galal Does this means that if there is no change in any lighting scene  it will give “Duplicate Scene Name“ error ?
Anyway please provide API to change the order.

**Comment by Mikisson** [comment]
**Ola Galal** _April 7, 2020, 5:48 AM_
Abdullah Asad 
Yes, that’s true. 
Okay, I will see with Ata and work on it.

**Comment by olagalal** [comment]
@godslave05 I think this is already done?

**Comment by godslave05** [comment]
https://github.com/oceanbuilders/ob-flutter-app/issues/160
