### ISSUE TITLE
Edit the text on error message

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#47]
This error is displayed on login page:

![8dbad97f-09b1-4c0a-ab40-3ae750ba4e2f](https://user-images.githubusercontent.com/72101387/96114915-80bbf280-0ee6-11eb-9767-9995dcb93e26.png)

Expected Result: ”Your email and password combination was incorrect. Please try again”

**Comment by diegopau** [comment]
From Ray:

"Test passed"

![IMG_2140](https://user-images.githubusercontent.com/315149/96747701-e3baf700-13c8-11eb-97ec-02e89ec5a044.png)
