### ISSUE TITLE
Toggle Notifications Seen Status

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#48]

**Comment by Mikisson** [comment]
**has to be done before:**
- Change Notification seen/unseen state - **DONE**

**relates to**
- Solve “Notification not found” bug in Toggle Notification Seen Status **DONE**

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 12:04 PM_
ready to be tested from the left side menu (notification list)

**Comment by Ray-LZ** [comment]
Test passed app version 0.7.0(8)
