### ISSUE TITLE
Add permission property to Access Request model

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#54]
Add the ability to send permission set id with “ new access invitation”, and with “accept access request api”

**Comment by Ray-LZ** [comment]
Hi @godslave05 please check this, access request is not working

**Comment by olagalal** [comment]
@Ray-LZ try this again

**Comment by Ray-LZ** [comment]
Hi @olagalal I just test "grant new access" & "access request" we still have the error message displayed.
![image](https://user-images.githubusercontent.com/46169036/99689782-06364380-2a4d-11eb-9dfa-084629c4e64b.png)

**Comment by olagalal** [comment]
@godslave05 did you add this from your type?

**Comment by godslave05** [comment]
"type" field added. Working for the existing user. For unknown user returning 404 ("No user found")
send invitation api is invoked with "seapodId",  "email",, "type" and "permissionID"
But what about the "access date" and "access duration" ? Is there a default settings in the server for this attributes ?
also there is "message" and "name" field in the UI.

**Comment by godslave05** [comment]
Implemented in 0.7+11

**Comment by godslave05** [comment]
@olagalal For unknown user the Send Access Invitation API is returning 404
