### ISSUE TITLE
Skip login (Demo)

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#55]

**Comment by diegopau** [comment]
Ray Zaragoza
4 days ago

Hi Ola Galal here was implemented fully the skip login feature? what’s the difference with OB-180
Ola Galal
2 days ago

Ray Zaragoza they are the same, duplicated 
Ray Zaragoza
2 days ago

Hi Kanika Tiwari I discarded this one (duplicated of OB-180)
