### ISSUE TITLE
Get Access Request/Invitation sent and received for specific user

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#59]
**_Linked issues_**

**relates to** 
Issue type: Task 
OB-183
Integrate get access request/invitation by user

**Comment by Mikisson** [comment]
**Ola Galal** _July 17, 2020, 8:25 AM_
Abdullah Asad  ​let me know if it works.

**Comment by Mikisson** [comment]
**Abdullah Asad** _July 18, 2020, 11:50 AM_
Ola Galal  ​It’s working.

**Comment by ray-scissorboy** [comment]
This is working as expected for previously created users that already have access to a seapod, @diegopau should we be able to grant access to a user that is not on our database at all?

**Comment by diegopau** [comment]
@olagalal even if the user that is invited doesn't have an account it has to be possible to give access to the invited user (status: pending)

**Comment by olagalal** [comment]
@diegopau I checked the api, it return the pending requests too.
@godslave05 please add this from your side on the app.

**Comment by Ray-LZ** [comment]
FYI @Bruno-N

**Comment by godslave05** [comment]
@olagalal  the api is returning 404 for unknown user.
*** DioError ***:
I/flutter ( 5649): uri: https://oceanbuilders.herokuapp.com/v1/api/access-requests/invitations/5ff6d6c26173bb0015e026c6
I/flutter ( 5649): DioError [DioErrorType.RESPONSE]: Http status error [404]
I/flutter ( 5649): uri: https://oceanbuilders.herokuapp.com/v1/api/access-requests/invitations/5ff6d6c26173bb0015e026c6
I/flutter ( 5649): statusCode: 404
I/flutter ( 5649): headers:
I/flutter ( 5649):  connection: keep-alive
I/flutter ( 5649):  x-powered-by: Express
I/flutter ( 5649):  date: Fri, 08 Jan 2021 09:04:36 GMT
I/flutter ( 5649):  access-control-allow-origin: *
I/flutter ( 5649):  content-length: 29
I/flutter ( 5649):  etag: W/"1d-0WCT/44QwvXlFBvrVl1Nr30x0BM"
I/flutter ( 5649):  via: 1.1 vegur
I/flutter ( 5649):  content-type: application/json; charset=utf-8
I/flutter ( 5649):  server: Cowboy
I/flutter ( 5649):
I/flutter ( 5649):
I/flutter ( 5649): show infor bar ---------------User Not Found!
