### ISSUE TITLE
Research: Open sourcing server authentication implementation. Consequences. What do other open source organizations do?

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#62]
Example: https://github.com/signalapp I would like to do research here, understand if they are fully disclosing not just the protocol they use but also absolutely all their server and app code in a way that any other team could copy it and deploy it and have it working.

I think a great example is cryptocurrencies in general. Popular cryptocurrencies like Ethereum https://github.com/ethereum or Iota https://github.com/iotaledger are fully open source, in fact nothing can be obscure in either their protocol or implementation. At the same time they involve complex cryptography and security implementations.

**Comment by diegopau** [comment]
From Ola:

@AtaMahmoud  Did you finish this card

**Comment by diegopau** [comment]
@AtaMahmoud are we good with this? did you finish your research and are we now sure that open sourcing is not a problem for the security of authentication?

**Comment by diegopau** [comment]
Ata said he is still looking into it. I keep it open and move to 0.8

**Comment by scottdear** [comment]
Does this still need to be done.  For Authentication it appears there is a bearer token scheme already implemented.  Also OpenIDC/Oauth 2.0 works well, with an authentication code flow. Is there more that needs to be done here?

**Comment by scottdear** [comment]
@Mikisson do we still need more research on this or can we close it out?
