### ISSUE TITLE
Open sourcing Server code in github

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#63]
**Issues in this epic:**

Issue type: Task
OB-192
Keep Express within its boundaries (Web Layer only)

Issue type: Task
OB-193
Create readme.md file

Issue type: Task
OB-194
centralized error object that derives from Node’s Error

Issue type: Task
OB-195
Document API using Swagger

Issue type: Task
OB-196
Exit the process gracefully when a stranger comes to town

Issue type: Task
OB-197
Add ESlint Plugins for Nodejs

Issue type: Task
OB-198
Move the salt rounds to an Environment variable

Issue type: Epic
OB-199
Use Code static analysis tools

Issue type: Task
OB-200
Move firebase configs to env variables

Issue type: Task
OB-201
publish the code to github and change heroku CI to github

**Comment by KanikaDevops** [comment]
Storypoints =35
