### ISSUE TITLE
Fix ios build issue 

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#7]

**Comment by Mikisson** [comment]
**Ray Zaragoza** _November 30, 2019, 10:10 AM_
Abdullah Asad could you please elaborate what to test, ot what is the fix?

**Comment by Mikisson** [comment]
**Abdullah Asad** _December 23, 2019, 9:26 AM_
After ios SDK update there are some issues related to the packages and configuration. They are fixed now as you can check the ios build already.

**Comment by godslave05** [comment]
this is done
