### ISSUE TITLE
Registration with sea pod creation

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#9]
Requirements link:  https://scissorboy.atlassian.net/wiki/spaces/O/pages/143753227/Registration+with+sea+pod+creation

Update: request example has been added to the postman collection.

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 6, 2020, 2:52 PM_
Test Pass
Post Registration with SeaPod Creation
https://oceanbuilders.herokuapp.com/v1/api/auth

![image-20200206-204951](https://user-images.githubusercontent.com/72101387/95998275-ff585780-0e34-11eb-8155-54d0ca2587da.png)

**Comment by KanikaDevops** [comment]
Storypointed

**Comment by Ray-LZ** [comment]
This is implemented
