### ISSUE TITLE
Save the Selected Weather Source

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#90]
The weather Screen and Marine Screen get data from Storm Glass Weather provider which is an external provider. Alternatively there is another source to get the data. That is weather flow station. This is treated as local provider as there is supposed to be a station placed on the seapod. From the application user can set priority of the sources to use. So an api is required to save the priority order and retrieve that after login/autologin.

**Comment by ray-scissorboy** [comment]
Hi @olagalal @godslave05 In the weather Provider Priority page, the user is able to tap and drag the provider, however, the changes are not saved when I kill the app and reopen it please confirm if this is an app or server issue

**Comment by olagalal** [comment]
@Ray-LZ I checked server side, no problem
@godslave05 please check app side

**Comment by Ray-LZ** [comment]
we should assign points for the server and app side

**Comment by godslave05** [comment]
This is not implemented in App. Currently the state is only saved in app memory.
Will integrate it  in next release

**Comment by godslave05** [comment]
implemented, @olagalal please allow the app to get the selected-weather-source. You may create a new issue for this.

**Comment by olagalal** [comment]
@godslave05 okay, working on this
