### ISSUE TITLE
Add Default LightScene while creating new user

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#94]

**Comment by Mikisson** [comment]
**Ola Galal** _September 19, 2020, 2:29 PM_
Diego Ocampo  I just added a random values, of you need to add specific values for the default lightScenes please inform me.

**Comment by Mikisson** [comment]
**Diego Ocampo** _September 21, 2020, 8:33 AM_
Hi, for now it is ok to have random values for now. Once we implement **OB-182: Template system for SeaPods. Initial templates**  we might start working with several models of SeaPods and when a user creates an account, depending on what SeaPod model is created, we will take all the values for the default light scenes (Day Mode, Night Mode) from the the template.

**Comment by ray-scissorboy** [comment]
Default day and night scenes have been added
App version 0.7.0(8)
