### ISSUE TITLE
Ola's Meetings Card [Oct, Nov]

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#96]

**Comment by Mikisson** [comment]
**Ola Galal** _October 3, 2020, 1:06 AM_

- 28/9 -> development team weekly meeting
- 2/10 > general meeting

**Comment by olagalal** [comment]
13 Oct: Hardware Team meeting

**Comment by olagalal** [comment]
19 Oct: Meeting (1h 50 min)
2 Nov: Dev Team Meeting (50 min)
3 Nov: Hardware Team Meeting (20 min)

**Comment by olagalal** [comment]
9 Nov: Dev Team Meeting (50 min)

**Comment by olagalal** [comment]
10 Nov: Hardware Team Meeting (1 hour 5 min)
10 Nov: Meeting with Bruno (44 min)
